import os
from dotenv import load_dotenv
from googleapiclient.discovery import build
from extraction_groups.academic_stress import get_academic_stress_comments_by_videos
from extraction_groups.career_employement_anxiety import get_career_employment_anxiety_comments_by_videos
from extraction_groups.depression_mental_health_discussions import get_depression_mental_health_discussions_comments_by_videos
from extraction_groups.financial_stress import get_financial_stress_comments_by_videos
from extraction_groups.lonliness_social_isolation import get_loneliness_social_isolation_comments_by_videos
from extraction_groups.neutral import get_neutral_comments_by_videos
from extraction_groups.positive_recovery_self_improvement import get_positive_recovery_self_improvement_comments_by_videos
from extraction_groups.relationship_breakup_issues import get_relationship_breakup_issues_comments_by_videos

load_dotenv()
youtube_comments_api_key = os.getenv("YOUTUBE_COMMENTS_API_KEY")

youtube = build("youtube","v3",developerKey=youtube_comments_api_key)

get_academic_stress_comments_by_videos(youtube)
get_career_employment_anxiety_comments_by_videos(youtube)
get_depression_mental_health_discussions_comments_by_videos(youtube)
get_financial_stress_comments_by_videos(youtube)
get_loneliness_social_isolation_comments_by_videos(youtube)
get_neutral_comments_by_videos(youtube)
get_positive_recovery_self_improvement_comments_by_videos(youtube)
get_relationship_breakup_issues_comments_by_videos(youtube)